FROM fukamachi/sbcl

RUN apt-get update && apt-get install -y libpq-dev curl

# install latest qlot
RUN curl -L https://qlot.tech/installer | sh

RUN mkdir /reddit
WORKDIR /reddit

RUN qlot install

COPY . /reddit

ENV PATH=/root/.roswell/bin:$PATH
ENV CL_SOURCE_REGISTRY=/reddit

