FROM reddit10-base:latest

RUN ros run -e '(ql-dist:install-dist "http://dist.luckylambda.technology/releases/lucky-lambda.txt" :prompt NIL)'

ENTRYPOINT [ "qlot", "exec", \
      "ros", "run", \
      "-e", "(ql:quickload :reddit)", \
      "-e", "(ql:quickload :reddit-db)", \
      "-e", "(ql:quickload :reddit-test)", \
      "-e", "(asdf:test-system :reddit-test)"]
