FROM reddit10-base:latest

EXPOSE 8000
EXPOSE 4005

ENTRYPOINT [ "qlot", "exec" , \
      "ros", "run", \
      "-e", "(ql:quickload :swank)", \
      "-e", "(setf swank::*loopback-interface* \"0.0.0.0\")", \
      "-e", "(swank:create-server :dont-close t :style :spawn)"]
