services:
  db:
    image: postgres:12.17-alpine3.19
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: "pgcwip42:"
    ports:
      - '5432:5432'
    volumes:
      - ../../tmp/db/test:/var/lib/postgresql/data
      - ../../script/db:/docker-entrypoint-initdb.d
    networks:
      - reddit10_test_nw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pgsql}"]
      interval: 1s
      timeout: 5s
      retries: 3
  pgweb:
    image: sosedoff/pgweb
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgres://pgsql:pgcwip42%3A@db:5432/reddit?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - reddit10_test_nw
networks:
  reddit10_test_nw:
    external: true
