name: test

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.21-alpine3.16
        env:
          POSTGRES_USER: pgsql
          POSTGRES_PASSWORD: "pgcwip42:"
          POSTGRES_DB: reddit_test
        options: >-
          --health-cmd pg-isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        lisp:
          - sbcl-bin

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v3
      - uses: niden/actions-memcached@v7
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: reddit-test
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: reddit-test
