name: test

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.21-alpine3.16
        env:
          POSTGRES_USER: pgsql
          POSTGRES_PASSWORD: "pgcwip42:"
          POSTGRES_DB: reddit_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v3
      - uses: niden/actions-memcached@v7
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: reddit
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: reddit
          run-tests: |
            (ql:quickload :reddit)
            (ql:quickload :reddit-db)
            (ql:quickload :reddit-test)
            (format T "pkg:~A" (list-all-packages))
            (in-package :reddit.main)
            (format T "current:~A" *package*)
            (do-symbols (s *package*)
              (print s))
            (reddit.main::connect-database)
        env:
          CL_SOURCE_REGISTRY: ${{ github.workspace }}
